EXTENSION = extractmonth_c
DATA = extractmonth_c--0.0.1.sql
OBJS = extractmonth_c.o
MODULE_big = extractmonth_c

PG_CONFIG = $(POSTGRESPATH)/bin/pg_config
PGXS :=$(shell $(PG_CONFIG) --pgxs)
include $(PGXS)